version: '3'
services:
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    build:
      context: ./images/influxdb/
      dockerfile: ./latest/Dockerfile
      args:
        INFLUXDB_TAG: influxdb:latest
    image: "influxdb"
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: "root"
      DOCKER_INFLUXDB_INIT_PASSWORD: "verysecretpassword"
      DOCKER_INFLUXDB_INIT_ORG: "biercool"
      DOCKER_INFLUXDB_INIT_BUCKET: "biercool"
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb2
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb2/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089/udp"
 
  vernemq:
    build:
      context: ./images/vernemq/
      dockerfile: ./latest/Dockerfile
      args:
        INFLUXDB_TAG: vernemq/vernemq:latest
    image: "vernemq"
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
    volumes:
      # Mount for vernemq configuration
      - ./vernemq/etc:/vernemq/etc
      - ./vernemq/data:/vernemq/data
      - ./vernemq/log:/vernemq/log
    ports:
      # The API for InfluxDB is served on port 8086
      - "8887:8888"
      - "8883:8883"
      - "1883:1883"

  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    build:
      context: ./images/telegraf/
      dockerfile: ./latest/Dockerfile
      args:
        TELEGRAF_TAG: telegraf:latest
    image: "telegraf"
    environment:
      HOSTNAME: "telegraf-getting-started"
    # Telegraf requires network access to InfluxDB
    links:
      - influxdb
      - vernemq
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
      - vernemq