version: '3'
services:
  influxdb:
    image: "influxdb:2.0.4"
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: "root"
      DOCKER_INFLUXDB_INIT_PASSWORD: "verysecretpassword"
      DOCKER_INFLUXDB_INIT_ORG: "biercool"
      DOCKER_INFLUXDB_INIT_BUCKET: "biercool"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ""
    volumes:
      # Mount for influxdb data directory
      - influxdb-data:/var/lib/influxdb2
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb2/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089/udp"
 
  vernemq:
    image: "vernemq/vernemq:1.11.0"
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
    volumes:
      # Mount for vernemq configuration
      - ./vernemq/etc:/vernemq/etc
      - vernemq-data:/vernemq/data
      - vernemq-logs:/vernemq/log
    ports:
      # The API for InfluxDB is served on port 8086
      - "8887:8888"
      - "8883:8883"
      - "1883:1883"

  telegraf:
    image: "telegraf:1.18.1"
    environment:
      HOSTNAME: "telegraf-getting-started"
    # Telegraf requires network access to InfluxDB
    links:
      - influxdb
      - vernemq
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
      - vernemq
volumes:
  influxdb-data:
  vernemq-data:
  vernemq-logs: